### ISSUE TITLE
Make tokenDecimals an optional parameter

### ISSUE THREAD

**Issue by Hugo0** [peanutprotocol/peanut-sdk#38]
`createLink` and similar functions don't need `tokenDecimals` parameter. We can optionally get it from on chain through an RPC call. Same for `tokenType`.

**Comment by js029** [comment]
@Hugo0 This issue has either already been addressed or needs clarification.
I found `tokenDecimals` passed as a parameter in 2 places:
1. `prepareApproveERC20Tx` where it already has a default (which is standard for ERC20 so no need to pull it from on chain)
2. `prepareTxs` where 'tokenDecimals` is present within the parameter of type `IPeanutLinkDetails`. Here it's optional and gets a hard-coded default value assigned in `validateLinkDetails` (both are sensible so again doesn't seem to need an on chain call).

The situation is similar for `tokenType`. I found it in:
1. `prepareTxs` where `tokenType` is present within the parameter of type `IPeanutLinkDetails`. Here it's not optional, but still gets a hard-coded default value assigned in `validateLinkDetails` (could make it optional or remove the default).

From what I can see `tokenType` is an internal mapping so I am guessing fetching it from on chain does not apply.
Looking forward to your comments!
