### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jeremy-Mrz** [peanutprotocol/peanut-sdk#61]
- [x] Problem: Gas fee calculation is not working on linea chain
Solution: Remove SDK gas calculation and let ethers handle it ;)

https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L547-L570

- [x] Problem: Slippage unused, can be confusing for users who use it in the SDK
Solution: Either remove or use it 

https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L2227

- [x] Problem: Cannot use claimXChain if not whitelisted
Solution: Because the SDK can be used by anyone, a dev should be able to enter his own  'x-integrator-id' to manage his own whitelisting

https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L2014
https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L2049
https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L2050
https://github.com/peanutprotocol/peanut-sdk/blob/main/src/index.ts#L2277

**Comment by nebolax** [comment]
Thanks a lot, Jerremy!

>  Problem: Slippage unused, can be confusing for users who use it in the SDK
> Solution: Either remove or use it

Already done in the new upcoming 0.4 sdk version! https://github.com/peanutprotocol/peanut-sdk/blob/0.4/src/index.ts#L1932

> Problem: Cannot use claimXChain if not whitelisted
> Solution: Because the SDK can be used by anyone, a dev should be able to enter his own 'x-integrator-id' to manage his own whitelisting

Squid has changed a bit their spam-prevention mechanism and now they do whitelisting by ip. x-integrator-id is solely informational now

For the first thing - about gas on linea - will look further

**Comment by nebolax** [comment]
Confirmed that there is a problem on linea

**Comment by nebolax** [comment]
> Problem: Gas fee calculation is not working on linea chain
> Solution: Remove SDK gas calculation and let ethers handle it ;)

Made a PR with a fix: https://github.com/peanutprotocol/peanut-sdk/pull/85

Unfortunately, at least in our experience, gas estimation in ethers was faulty often times (i.e. the gas values were too low and transactions were not included in blocks), so we had to have a custom gas estimation method :(
